# Generated by Django 4.1.6 on 2023-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
