# Generated by Django 4.1.6 on 2023-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_postfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='rating',
        ),
        migrations.AddField(
            model_name='articles',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
