# Generated by Django 4.1.6 on 2023-07-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
