# Generated by Django 4.1.6 on 2023-07-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_delete_feedback'),
        ('articles', '0004_remove_feedback_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.articles'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='commentator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='readers.profile'),
        ),
    ]
