# Generated by Django 4.1.6 on 2023-07-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_delete_feedback'),
        ('articles', '0005_remove_feedback_user_feedback_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.profile'),
        ),
    ]
