# Generated by Django 4.1.6 on 2023-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Отвратительно'), (2, 'Плохо'), (3, 'Так себе'), (4, 'Неплохо'), (5, 'Отлично!')]),
        ),
    ]
