# Generated by Django 4.1.6 on 2023-07-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
